name: forecast
description:
  en: "This forecast is based on open source code."
developers:
  - name: Givero
    url: https://github.com/giverosearch/instant-answers
  - name: DuckDuckGo
    url: https://github.com/duckduckgo/zeroclickinfo-spice
  - name: DeviantArt
    url: https://www.deviantart.com/merlinthered/art/plain-weather-icons-157162192
homepage: https://github.com/giverosearch
triggers:
  match: /^(?<city_name>[\wæøåÆØÅ]+(?:[\s-][\wæøåÆØÅ]+)*)?\s*(?<main_trigger>weather|forecast|weather forecast|weer|meteo|wetter|clima|vejr|vejret|vejrudsigt|vejrudsigten)\s*\g'city_name'?$/i
imports:
  var:
    - USER_GEOLOCATION_LATITUDE
    - USER_GEOLOCATION_LONGITUDE
    - USER_COUNTRY_NAME
    - USER_CITY_NAME
    - USER_BROWSER_LANGUAGE
declarations:
  env:
    - AI_FORECAST_DARKSKY_APIKEY
    - AI_FORECAST_GOOGLE_APIKEY
  proxy:
    darksky: https://api.darksky.net/forecast/{{ENV(AI_FORECAST_DARKSKY_APIKEY)}}
    google: https://maps.googleapis.com/maps/api/geocode/json?key={{ENV(AI_FORECAST_GOOGLE_APIKEY)}}
